//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace MULE_Controller.muleServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MULEWcfServiceLibrary")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPost", Namespace="http://schemas.datacontract.org/2004/07/MULEWcfServiceLibrary")]
    public partial class DataPost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float avgField;
        
        private string dataTypeField;
        
        private string datetimeField;
        
        private float depthField;
        
        private string descriptionField;
        
        private System.Collections.ObjectModel.ObservableCollection<int> detailsValuesField;
        
        private float eastingsField;
        
        private string group_nameField;
        
        private string metaDataField;
        
        private float northingsField;
        
        private float sdField;
        
        private float semField;
        
        private int sensorField;
        
        private string serialField;
        
        private string user_nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float avg {
            get {
                return this.avgField;
            }
            set {
                if ((this.avgField.Equals(value) != true)) {
                    this.avgField = value;
                    this.RaisePropertyChanged("avg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.dataTypeField, value) != true)) {
                    this.dataTypeField = value;
                    this.RaisePropertyChanged("dataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((object.ReferenceEquals(this.datetimeField, value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float depth {
            get {
                return this.depthField;
            }
            set {
                if ((this.depthField.Equals(value) != true)) {
                    this.depthField = value;
                    this.RaisePropertyChanged("depth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<int> detailsValues {
            get {
                return this.detailsValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.detailsValuesField, value) != true)) {
                    this.detailsValuesField = value;
                    this.RaisePropertyChanged("detailsValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float eastings {
            get {
                return this.eastingsField;
            }
            set {
                if ((this.eastingsField.Equals(value) != true)) {
                    this.eastingsField = value;
                    this.RaisePropertyChanged("eastings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_name {
            get {
                return this.group_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.group_nameField, value) != true)) {
                    this.group_nameField = value;
                    this.RaisePropertyChanged("group_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string metaData {
            get {
                return this.metaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.metaDataField, value) != true)) {
                    this.metaDataField = value;
                    this.RaisePropertyChanged("metaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float northings {
            get {
                return this.northingsField;
            }
            set {
                if ((this.northingsField.Equals(value) != true)) {
                    this.northingsField = value;
                    this.RaisePropertyChanged("northings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sd {
            get {
                return this.sdField;
            }
            set {
                if ((this.sdField.Equals(value) != true)) {
                    this.sdField = value;
                    this.RaisePropertyChanged("sd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sem {
            get {
                return this.semField;
            }
            set {
                if ((this.semField.Equals(value) != true)) {
                    this.semField = value;
                    this.RaisePropertyChanged("sem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sensor {
            get {
                return this.sensorField;
            }
            set {
                if ((this.sensorField.Equals(value) != true)) {
                    this.sensorField = value;
                    this.RaisePropertyChanged("sensor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                if ((object.ReferenceEquals(this.serialField, value) != true)) {
                    this.serialField = value;
                    this.RaisePropertyChanged("serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_nameField, value) != true)) {
                    this.user_nameField = value;
                    this.RaisePropertyChanged("user_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="muleServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MULE_Controller.muleServiceReference.CompositeType> GetDataUsingDataContractAsync(MULE_Controller.muleServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkLogin", ReplyAction="http://tempuri.org/IService1/checkLoginResponse")]
        System.Threading.Tasks.Task<string> checkLoginAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGroups", ReplyAction="http://tempuri.org/IService1/getGroupsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<string>> getGroupsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/uploadPosts", ReplyAction="http://tempuri.org/IService1/uploadPostsResponse")]
        System.Threading.Tasks.Task<bool> uploadPostsAsync(MULE_Controller.muleServiceReference.DataPost dp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MULE_Controller.muleServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MULE_Controller.muleServiceReference.IService1>, MULE_Controller.muleServiceReference.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<MULE_Controller.muleServiceReference.CompositeType> GetDataUsingDataContractAsync(MULE_Controller.muleServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<string> checkLoginAsync(string username) {
            return base.Channel.checkLoginAsync(username);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<string>> getGroupsAsync(string username) {
            return base.Channel.getGroupsAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> uploadPostsAsync(MULE_Controller.muleServiceReference.DataPost dp) {
            return base.Channel.uploadPostsAsync(dp);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/MULEWcfServiceLibrary/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
